### ISSUE TITLE
Where can I find the training dataset?

### ISSUE THREAD

**Issue by yzheng97** [ZongxuPan/DrBox-v2-tensorflow#10]
I want to train DrBox-v2 end-to-end. Could you please provide the download link of 3 datasets mentioned in the paper?

**Comment by Anquanzhi** [comment]
I'm afraid we can't provide you with the data, because the data of GF-3 and aircraft data are purchased from relevant institutions and cannot be uploaded completely.You can use the publicly available SSDD datasets on the Internet.

**Comment by yzheng97** [comment]
Thanks for your reply. The thing is I could not find the download link or project website of SSDD anywhere.

**Comment by Anquanzhi** [comment]
https://pan.baidu.com/s/10jmYNU49f_RtFJHbOER0MA 
password:71kj

**Comment by yzheng97** [comment]
> https://pan.baidu.com/s/10jmYNU49f_RtFJHbOER0MA
> password:71kj

Many thanks
