### ISSUE TITLE
Hi, the Baidu Pan download link is already invalid. Could you update a valid one? Thanks

### ISSUE THREAD

**Issue by sidney001** [ZongxuPan/DrBox-v2-tensorflow#2]
I suggest you to upload model weights file to Google Drive, Dropbox or Onedrive

**Comment by Anquanzhi** [comment]
You can download the file at https://pan.baidu.com/s/1yMcGfwzURuHDriZQSsJERg, and the password is '8vbr'.
We will refer to your comments and upload the weights file on a new platform

**Comment by ZongxuPan** [comment]
> 
> 
> I suggest you to upload model weights file to Google Drive, Dropbox or Onedrive

Thank you for your question and suggestion. Please see the above comment by Anquanzhi. Besides, the file "vgg16.npy" is the pretrained model of VGG16, and we downloaded it from the internet. You could obtain it by searching the internet, for example searching in the github.

**Comment by sidney001** [comment]
Thanks @Anquanzhi @ZongxuPan . I thought you finetune the vgg model and I pull this issue.
